using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MyMVVMSourceGenerators;

[Generator]
public class MyMVVMSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => new ModelGenConfig(ctx))
            .Where(m => m.ShouldGen)
            .Collect();
        
        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<ModelGenConfig> modelGenConfigs)
    {
        foreach (ModelGenConfig modelGenConfig in modelGenConfigs)
        {
            var sourceBuilder = new StringBuilder();
            
            sourceBuilder.Append($@"// AutoGenerated code by MyMVVM.
{FormatFieldNamespaces(modelGenConfig)}{FormatNamespaceString(modelGenConfig)}
public partial class {modelGenConfig.ClassName}{FormatParentClassString(modelGenConfig)}
{{");
            foreach (var attrConfig in modelGenConfig.RelevantAttributes)
            {
                if (attrConfig is ObservableAttributeConfig observableAttr)
                {
                    if (observableAttr.IsList)
                    {
                        if (observableAttr.FieldIsTypeModel)
                        {
                            sourceBuilder.Append(GenerateModelObservableList(observableAttr));
                        }
                        else
                        {
                            sourceBuilder.Append(GenerateObservableList(observableAttr));
                        }
                    }
                    else
                    {
                        if (observableAttr.FieldIsTypeModel)
                        {
                            sourceBuilder.Append(GenerateModelObservable(observableAttr));
                        }
                        else
                        {
                            sourceBuilder.Append(GenerateObservable(observableAttr));
                        }
                    }
                }
                else if (attrConfig is PassthroughAttributeConfig passthroughAttr)
                {
                    if (passthroughAttr.IsList)
                    {
                        sourceBuilder.Append(GeneratePassthroughList(passthroughAttr));
                    }
                    else
                    {
                        sourceBuilder.Append(GeneratePassthrough(passthroughAttr));
                    }
                }
            }

            sourceBuilder.Append(GenerateModelInit(modelGenConfig));
            sourceBuilder.Append($@"{FormatNamespaceStringEnder(modelGenConfig)}
}}");
            
            context.AddSource($"{modelGenConfig.ClassName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }
    }
    
    private string FormatNamespaceString(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.Namespace) ? "" : @$"
namespace {modelGenConfig.Namespace}
{{";
    }

    private string FormatNamespaceStringEnder(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.Namespace) ? "" : "}";
    }

    private string FormatParentClassString(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.ParentClassName) ? "" : $" : {modelGenConfig.ParentClassName}";
    }

    private string FormatFieldNamespaces(ModelGenConfig modelGenConfig)
    {
        HashSet<string> namespaces = new();
        namespaces.Add("MyMVVM");
        namespaces.Add("System");
        if (modelGenConfig.RelevantAttributes.Any(x => x.IsList))
        {
            namespaces.Add("System.Collections.ObjectModel");
        }
        foreach(AttributeConfig attrConfig in modelGenConfig.RelevantAttributes)
        {
            if (!string.IsNullOrEmpty(attrConfig.TypeNamespace))
            {
                namespaces.Add(attrConfig.TypeNamespace);
            }
        }

        namespaces.Remove("<global namespace>");
        
        StringBuilder stringBuilder = new();
        foreach(string namespaceStr in namespaces)
        {
            stringBuilder.Append($"using {namespaceStr};\n");
        }
        return stringBuilder.ToString();
    }

    private string GenerateModelObservable(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated for {observable.FieldName} ===
    public {observable.FieldType} {observable.PropName} => {observable.FieldName};
    
    public void {observable.PropName}_Set({observable.FieldType} value, bool notify = true)
    {{
        if ({observable.FieldName} != null)
        {{
            {observable.FieldName}.OnChanged -= OnChanged;
        }}

        {observable.FieldName} = value;
        {observable.FieldName}.OnChanged += OnChanged;

        if (notify)
        {{
            OnChanged?.Invoke(this);
        }}
    }}
    // ====================
";
    }
    private string GenerateObservable(ObservableAttributeConfig observable)
    { 
        return $@"
    // === Generated for {observable.FieldName} ===
    public {observable.FieldType} {observable.PropName} => {observable.FieldName};
    public Action<{observable.FieldType}> {observable.PropName}_OnChanged;
    
    public void {observable.PropName}_Set({observable.FieldType} value, bool notify = true)
    {{
        {observable.FieldName} = value;
        if (notify)
        {{
            {observable.PropName}_TriggerOnChanged();
        }}
    }}

    public void {observable.PropName}_TriggerOnChanged()
    {{
        {observable.PropName}_OnChanged?.Invoke({observable.FieldName});
        OnChanged?.Invoke(this);
    }}
    // ====================
";
    }

    private string GenerateModelObservableList(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated for {observable.FieldName} {observable.FieldIsTypeModel}===
    private ReadOnlyCollection<{observable.ListType}> {observable.PropName}_ReadOnly;
    public ReadOnlyCollection<{observable.ListType}> {observable.PropName}
    {{
        get
        {{
            if ({observable.PropName}_ReadOnly == null)
            {{
                {observable.PropName}_ReadOnly = {observable.FieldName}.AsReadOnly();
            }}
            return {observable.PropName}_ReadOnly;
        }}
    }}

    public Action {observable.PropName}_OnChanged;
    public Action<int, {observable.ListType}> {observable.PropName}_OnElementInserted;
    public Action<int> {observable.PropName}_OnElementRemoved;
    public Action<int> {observable.PropName}_OnElementChanged;
    
    public void {observable.PropName}_Set(List<{observable.ListType}> value, bool notify = true)
    {{
        {observable.PropName}_Clear(false);

        {observable.FieldName} = value;

        if ({observable.FieldName} != null)
        {{
            foreach ({observable.ListType} element in {observable.FieldName})
            {{
                {observable.PropName}_BindElementOnChanged(element);
            }}
        }}

        if (notify)
        {{
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Add({observable.ListType} value, bool notify = true)
    {{
        {observable.PropName}_Insert({observable.FieldName}.Count, value, notify);
    }}
        
    public void {observable.PropName}_Insert(int index, {observable.ListType} value, bool notify = true)
    {{
        {observable.FieldName}.Insert(index, value);
        {observable.PropName}_BindElementOnChanged(value);

        if (notify)
        {{
            {observable.PropName}_OnElementInserted?.Invoke(index, value);
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Remove({observable.ListType} value, bool notify = true)
    {{
        int index = {observable.FieldName}.IndexOf(value);
        {observable.PropName}_RemoveAt(index, notify);
    }}
        
    public void {observable.PropName}_RemoveAt(int index, bool notify = true)
    {{
        if (index == -1)
        {{
            return;
        }}

        {observable.ListType} elementToRemove = {observable.FieldName}[index];
        {observable.FieldName}.RemoveAt(index);
        {observable.PropName}_UnbindElementOnChanged(elementToRemove);

        if (notify)
        {{
            {observable.PropName}_OnElementRemoved?.Invoke(index);
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}

    public void {observable.PropName}_Set(int index, {observable.ListType} value, bool notify = true)
    {{
        {observable.PropName}_UnbindElementOnChanged({observable.FieldName}[index]);
        {observable.FieldName}[index] = value;
        {observable.PropName}_BindElementOnChanged(value);

        if (notify)
        {{
            {observable.PropName}_TriggerElementChanged(value);
        }}
    }}
        
    public void {observable.PropName}_Clear(bool notify = true)
    {{
        if ({observable.FieldName} == null)
        {{
            return;
        }}

        foreach ({observable.ListType} element in {observable.FieldName})
        {{
            {observable.PropName}_UnbindElementOnChanged(element);
        }}

        {observable.FieldName}.Clear();
        if (notify)
        {{
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}

    private void {observable.PropName}_BindElementOnChanged({observable.ListType} element)
    {{
        if (element == null)
        {{
            return;
        }}

        element.OnChanged += {observable.PropName}_TriggerElementChanged_Wrapper;
    }}

    private void {observable.PropName}_UnbindElementOnChanged({observable.ListType} element)
    {{
        if (element == null)
        {{
            return;
        }}

        element.OnChanged -= {observable.PropName}_TriggerElementChanged_Wrapper;
    }}

    private void {observable.PropName}_TriggerElementChanged_Wrapper(BaseDataModel baseDataModel)
    {{
        {observable.PropName}_TriggerElementChanged(baseDataModel as {observable.ListType});
    }}

    public void {observable.PropName}_TriggerElementChanged({observable.ListType} element)
    {{
        int index = {observable.FieldName}.IndexOf(element);
        if (index == -1)
        {{
            return;
        }}

        {observable.PropName}_OnElementChanged?.Invoke(index);
        {observable.PropName}_OnChanged?.Invoke();
        OnChanged?.Invoke(this);
    }}
    // ====================
";
    }
    private string GenerateObservableList(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated for {observable.FieldName} {observable.FieldIsTypeModel}===
    private ReadOnlyCollection<{observable.ListType}> {observable.PropName}_ReadOnly;
    public ReadOnlyCollection<{observable.ListType}> {observable.PropName}
    {{
        get
        {{
            if ({observable.PropName}_ReadOnly == null)
            {{
                {observable.PropName}_ReadOnly = {observable.FieldName}.AsReadOnly();
            }}
            return {observable.PropName}_ReadOnly;
        }}
    }}
        
    public Action {observable.PropName}_OnChanged;
    public Action<int, {observable.ListType}> {observable.PropName}_OnElementInserted;
    public Action<int> {observable.PropName}_OnElementRemoved;
    public Action<int> {observable.PropName}_OnElementChanged;
    
    public void {observable.PropName}_Set(List<{observable.ListType}> value, bool notify = true)
    {{
        {observable.FieldName} = value;
        if (notify)
        {{
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Add({observable.ListType} value, bool notify = true)
    {{
        {observable.PropName}_Insert({observable.FieldName}.Count, value, notify);
    }}
        
    public void {observable.PropName}_Insert(int index, {observable.ListType} value, bool notify = true)
    {{
        {observable.FieldName}.Insert(index, value);
        if (notify)
        {{
            {observable.PropName}_OnElementInserted?.Invoke(index, value);
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Remove({observable.ListType} value, bool notify = true)
    {{
        int index = {observable.FieldName}.IndexOf(value);
        {observable.PropName}_RemoveAt(index, notify);
    }}
        
    public void {observable.PropName}_RemoveAt(int index, bool notify = true)
    {{
        if (index == -1)
        {{
            return;
        }}

        {observable.FieldName}.RemoveAt(index);
        if (notify)
        {{
            {observable.PropName}_OnElementRemoved?.Invoke(index);
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}

    public void {observable.PropName}_Set(int index, {observable.ListType} value, bool notify = true)
    {{
        {observable.FieldName}[index] = value;
        if (notify)
        {{
            {observable.PropName}_TriggerElementChanged(value);
        }}
    }}
        
    public void {observable.PropName}_Clear(bool notify = true)
    {{
        if ({observable.FieldName} == null)
        {{
            return;
        }}

        {observable.FieldName}.Clear();
        if (notify)
        {{
            {observable.PropName}_OnChanged?.Invoke();
            OnChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_TriggerElementChanged({observable.ListType} element)
    {{
        int index = {observable.FieldName}.IndexOf(element);
        if (index == -1)
        {{
            return;
        }}

        {observable.PropName}_OnElementChanged?.Invoke(index);
        {observable.PropName}_OnChanged?.Invoke();
        OnChanged?.Invoke(this);
    }}
    // ====================
";
    }

    private string GeneratePassthrough(PassthroughAttributeConfig passthrough)
    {
        return $@"
    // === Generated for {passthrough.FieldName} ===
    public {passthrough.FieldType} {passthrough.PropName} => {passthrough.ModelName}.{passthrough.ModelPropertyName};
    public Action<{passthrough.FieldType}> {passthrough.PropName}_OnChanged
    {{
        get => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged;
        set => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged = value;
    }}
    
    public void {passthrough.PropName}_Set({passthrough.FieldType} value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(value, notify);
    }}

    public void {passthrough.PropName}_TriggerChanged()
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_TriggerOnChanged();
    }}
    // ====================
";
    }

    private string GeneratePassthroughList(PassthroughAttributeConfig passthrough)
    {
        return $@"
    // === Generated for {passthrough.FieldName} ===
    public ReadOnlyCollection<{passthrough.ListType}> {passthrough.PropName} => {passthrough.ModelName}.{passthrough.ModelPropertyName};
    public Action {passthrough.PropName}_OnChanged
    {{
        get => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged;
        set => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged = value;
    }}
    public Action<int, {passthrough.ListType}> {passthrough.PropName}_OnElementInserted
    {{
        get => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementInserted;
        set => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementInserted = value;
    }}
    public Action<int> {passthrough.PropName}_OnElementRemoved
    {{
        get => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementRemoved;
        set => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementRemoved = value;
    }}
    public Action<int> {passthrough.PropName}_OnElementChanged
    {{
        get => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementChanged;
        set => {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementChanged = value;
    }}
        
    public void {passthrough.PropName}_Set(List<{passthrough.ListType}> value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(value, notify);
    }}
        
    public void {passthrough.PropName}_Add({passthrough.ListType} value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Add(value, notify);
    }}
        
    public void {passthrough.PropName}_Insert(int index, {passthrough.ListType} value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Insert(index, value, notify);
    }}
        
    public void {passthrough.PropName}_Remove({passthrough.ListType} value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Remove(value, notify);
    }}
        
    public void {passthrough.PropName}_RemoveAt(int index, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_RemoveAt(index, notify);
    }}
        
    public void {passthrough.PropName}_Set(int index, {passthrough.ListType} value, bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(index, value, notify);
    }}
        
    public void {passthrough.PropName}_Clear(bool notify = true)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Clear(notify);
    }}
        
    public void {passthrough.PropName}_TriggerElementChanged({passthrough.ListType} element)
    {{
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_TriggerElementChanged(element);
    }}
    // =================
";
    }
    
    private string GenerateModelInit(ModelGenConfig modelGenConfig)
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append($@"
    protected override void AutoGenInit()
    {{");
        
        foreach (AttributeConfig attributeConfig in modelGenConfig.RelevantAttributes)
        {
            if (attributeConfig is ObservableAttributeConfig observable && observable.FieldIsTypeModel)
            {
                if (observable.IsList)
                {
                    stringBuilder.Append($@"
    if ({observable.FieldName} != null)
    {{
        foreach({observable.ListType} element in {observable.FieldName})
        {{
            {observable.PropName}_BindElementOnChanged(element);
        }}
    }}");
                }
                else
                {
                    stringBuilder.Append($@"
    if ({observable.FieldName} != null)
    {{
        {observable.FieldName}.OnChanged += OnChanged;
    }}");
                }
            }
        }
        
        stringBuilder.Append($@"
}}");   
        
        return stringBuilder.ToString();
    }
}