using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MyMVVMSourceGenerators;

[Generator]
public class MyMVVMSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => new ModelGenConfig(ctx))
            .Where(m => m.ShouldGen)
            .Collect();
        
        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<ModelGenConfig> modelGenConfigs)
    {
        foreach (ModelGenConfig modelGenConfig in modelGenConfigs)
        {
            var sourceBuilder = new StringBuilder();
            
            sourceBuilder.Append($@"// AutoGenerated code by MyMVVM.
{FormatFieldNamespaces(modelGenConfig)}{FormatNamespaceString(modelGenConfig)}
public partial class {modelGenConfig.ClassName}
{{");
            foreach (var attrConfig in modelGenConfig.RelevantAttributes)
            {
                if (attrConfig is ObservableAttributeConfig observableAttr)
                {
                    if (observableAttr.IsList)
                    {
                        if (observableAttr.FieldIsTypeModel)
                        {
                            sourceBuilder.Append(GenerateModelObservableList(observableAttr));
                        }
                        else
                        {
                            sourceBuilder.Append(GenerateObservableList(observableAttr));
                        }
                    }
                    else
                    {
                        if (observableAttr.FieldIsTypeModel)
                        {
                            sourceBuilder.Append(GenerateModelObservable(observableAttr));
                        }
                        else
                        {
                            sourceBuilder.Append(GenerateObservable(observableAttr));
                        }
                    }
                }
                else if (attrConfig is PassthroughAttributeConfig passthroughAttr)
                {
                    if (passthroughAttr.IsList)
                    {
                        sourceBuilder.Append(GeneratePassthroughList(passthroughAttr));
                    }
                    else
                    {
                        sourceBuilder.Append(GeneratePassthrough(passthroughAttr));
                    }
                }
            }

            sourceBuilder.Append(GenerateModelInit(modelGenConfig));
            sourceBuilder.Append(GenerateModelOnChangedAction(modelGenConfig));
            sourceBuilder.Append(GenerateSafeEqualityComparerFunction());
            sourceBuilder.Append($@"{FormatNamespaceStringEnder(modelGenConfig)}
}}");
            
            context.AddSource($"{modelGenConfig.ClassName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }
    }
    
    private string FormatNamespaceString(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.Namespace) ? "" : @$"
namespace {modelGenConfig.Namespace}
{{";
    }

    private string FormatNamespaceStringEnder(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.Namespace) ? "" : "}";
    }

    private string FormatParentClassString(ModelGenConfig modelGenConfig)
    {
        return string.IsNullOrEmpty(modelGenConfig.ParentClassName) ? "" : $" : {modelGenConfig.ParentClassName}";
    }

    private string FormatFieldNamespaces(ModelGenConfig modelGenConfig)
    {
        HashSet<string> namespaces = new();
        namespaces.Add("MyMVVM");
        namespaces.Add("System");
        namespaces.Add("System.Collections.Generic");
        if (modelGenConfig.RelevantAttributes.Any(x => x.IsList))
        {
            namespaces.Add("System.Collections.ObjectModel");
        }
        foreach(AttributeConfig attrConfig in modelGenConfig.RelevantAttributes)
        {
            if (!string.IsNullOrEmpty(attrConfig.TypeNamespace))
            {
                namespaces.Add(attrConfig.TypeNamespace);
            }
        }

        namespaces.Remove("<global namespace>");
        
        StringBuilder stringBuilder = new();
        foreach(string namespaceStr in namespaces)
        {
            stringBuilder.Append($"using {namespaceStr};\n");
        }
        return stringBuilder.ToString();
    }

    private string GenerateModelObservable(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated Observable for {observable.FieldName} ===
    public {observable.FieldType} {observable.PropName} => {observable.FieldName};
    
    public void {observable.PropName}_Set({observable.FieldType} value, bool notify = true)
    {{
        if (SafeEquals({observable.FieldName}, value))
        {{
            return;
        }}

        if ({observable.FieldName} != null)
        {{
            {observable.FieldName}.OnChanged -= m_onChanged;
        }}

        {observable.FieldName} = value;
        {observable.FieldName}.OnChanged += m_onChanged;

        if (notify)
        {{
            m_onChanged?.Invoke(this);
        }}
    }}
    // ====================
";
    }

    private string GenerateOnChangedAction(string callbackName, string fieldType)
    {
        if (!string.IsNullOrEmpty(fieldType))
        {
            fieldType = $"<{fieldType}>";
        }
        
        return $@"private Action{fieldType} m_{callbackName};
    private Action m_{callbackName}_OnDelegatesChanged;
    public event Action{fieldType} {callbackName}
    {{
        add
        {{
            m_{callbackName} += value;
            m_{callbackName}_OnDelegatesChanged?.Invoke();
        }}
        remove
        {{
            m_{callbackName} -= value;
            m_{callbackName}_OnDelegatesChanged?.Invoke();
        }}
    }}";
    }
    
    private string GenerateObservable(ObservableAttributeConfig observable)
    { 
        return $@"
    // === Generated Observable for {observable.FieldName} ===
    public {observable.FieldType} {observable.PropName} => {observable.FieldName};

    {GenerateOnChangedAction($"{observable.PropName}_OnChanged", observable.FieldType)}
    
    public void {observable.PropName}_Set({observable.FieldType} value, bool notify = true)
    {{
        if (SafeEquals({observable.FieldName}, value))
        {{
            return;
        }}

        {observable.FieldName} = value;
        if (notify)
        {{
            {observable.PropName}_TriggerOnChanged();
        }}
    }}

    public void {observable.PropName}_TriggerOnChanged()
    {{
        m_{observable.PropName}_OnChanged?.Invoke({observable.FieldName});
        m_onChanged?.Invoke(this);
    }}
    // ====================
";
    }

    private string GenerateModelObservableList(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated Observable for {observable.FieldName} ===
    private ReadOnlyCollection<{observable.ListType}> {observable.PropName}_ReadOnly;
    public ReadOnlyCollection<{observable.ListType}> {observable.PropName}
    {{
        get
        {{
            if ({observable.PropName}_ReadOnly == null && {observable.FieldName} != null)
            {{
                {observable.PropName}_ReadOnly = {observable.FieldName}.AsReadOnly();
            }}
            return {observable.PropName}_ReadOnly;
        }}
    }}

    //public Action {observable.PropName}_OnChanged;
    {GenerateOnChangedAction($"{observable.PropName}_OnChanged", "")}
    //public Action<int, {observable.ListType}> {observable.PropName}_OnElementInserted;
    {GenerateOnChangedAction($"{observable.PropName}_OnElementInserted", $"int, {observable.ListType}")}
    //public Action<int> {observable.PropName}_OnElementRemoved;
    {GenerateOnChangedAction($"{observable.PropName}_OnElementRemoved", $"int")}
    //public Action<int> {observable.PropName}_OnElementChanged;
    {GenerateOnChangedAction($"{observable.PropName}_OnElementChanged", $"int")}
    
    public void {observable.PropName}_Set(List<{observable.ListType}> value, bool notify = true)
    {{
        if (SafeEquals({observable.FieldName}, value))
        {{
            return;
        }}

        if ({observable.FieldName} == null)
        {{
            {observable.FieldName} = new();
        }}

        {observable.PropName}_Clear(false);

        foreach ({observable.ListType} element in value)
        {{
            {observable.PropName}_Add(element, false);
        }}

        if (notify)
        {{
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Add({observable.ListType} value, bool notify = true)
    {{
        {observable.PropName}_Insert({observable.FieldName}.Count, value, notify);
    }}
        
    public void {observable.PropName}_Insert(int index, {observable.ListType} value, bool notify = true)
    {{
        if (index < 0 || index > {observable.FieldName}.Count)
        {{
            return;
        }}

        {observable.FieldName}.Insert(index, value);
        {observable.PropName}_BindElementOnChanged(value);

        if (notify)
        {{
            m_{observable.PropName}_OnElementInserted?.Invoke(index, value);
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Remove({observable.ListType} value, bool notify = true)
    {{
        int index = {observable.FieldName}.IndexOf(value);
        {observable.PropName}_RemoveAt(index, notify);
    }}
        
    public void {observable.PropName}_RemoveAt(int index, bool notify = true)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }}

        {observable.ListType} elementToRemove = {observable.FieldName}[index];
        {observable.FieldName}.RemoveAt(index);
        {observable.PropName}_UnbindElementOnChanged(elementToRemove);

        if (notify)
        {{
            m_{observable.PropName}_OnElementRemoved?.Invoke(index);
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}

    public void {observable.PropName}_Set(int index, {observable.ListType} value, bool notify = true)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }}

        if (SafeEquals({observable.FieldName}[index], value))
        {{
            return;
        }}

        {observable.PropName}_UnbindElementOnChanged({observable.FieldName}[index]);
        {observable.FieldName}[index] = value;
        {observable.PropName}_BindElementOnChanged(value);

        if (notify)
        {{
            {observable.PropName}_TriggerElementChanged(index);
        }}
    }}
        
    public void {observable.PropName}_Clear(bool notify = true)
    {{
        if ({observable.FieldName} == null)
        {{
            return;
        }}

        foreach ({observable.ListType} element in {observable.FieldName})
        {{
            {observable.PropName}_UnbindElementOnChanged(element);
        }}

        {observable.FieldName}.Clear();
        if (notify)
        {{
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}

    private void {observable.PropName}_BindElementOnChanged({observable.ListType} element)
    {{
        if (element == null)
        {{
            return;
        }}

        element.OnChanged += {observable.PropName}_TriggerElementChanged_Wrapper;
    }}

    private void {observable.PropName}_UnbindElementOnChanged({observable.ListType} element)
    {{
        if (element == null)
        {{
            return;
        }}

        element.OnChanged -= {observable.PropName}_TriggerElementChanged_Wrapper;
    }}

    private void {observable.PropName}_TriggerElementChanged_Wrapper(BaseModel baseModel)
    {{
        int index = {observable.FieldName}.IndexOf(baseModel);
        if (index == -1)
        {{
            return;
        }}

        {observable.PropName}_TriggerElementChanged(index);
    }}

    public void {observable.PropName}_TriggerElementChanged(int index)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }}

        m_{observable.PropName}_OnElementChanged?.Invoke(index);
        m_{observable.PropName}_OnChanged?.Invoke();
        m_onChanged?.Invoke(this);
    }}
    // ====================
";
    }
    private string GenerateObservableList(ObservableAttributeConfig observable)
    {
        return $@"
    // === Generated Observable for {observable.FieldName} ===
    private ReadOnlyCollection<{observable.ListType}> {observable.PropName}_ReadOnly;
    public ReadOnlyCollection<{observable.ListType}> {observable.PropName}
    {{
        get
        {{
            if ({observable.PropName}_ReadOnly == null && {observable.FieldName} != null)
            {{
                {observable.PropName}_ReadOnly = {observable.FieldName}.AsReadOnly();
            }}
            return {observable.PropName}_ReadOnly;
        }}
    }}

    {GenerateOnChangedAction($"{observable.PropName}_OnChanged", "")}
    {GenerateOnChangedAction($"{observable.PropName}_OnElementInserted", $"int, {observable.ListType}")}
    {GenerateOnChangedAction($"{observable.PropName}_OnElementRemoved", $"int")}
    {GenerateOnChangedAction($"{observable.PropName}_OnElementChanged", $"int")}
    
    public void {observable.PropName}_Set(List<{observable.ListType}> value, bool notify = true)
    {{
        if (SafeEquals({observable.FieldName}, value))
        {{
            return;
        }}

        if (value == null)
        {{
            {observable.FieldName} = null;
            {observable.PropName}_ReadOnly = null;
        }}
        else
        {{
            if ({observable.FieldName} == null)
            {{
                {observable.FieldName} = new();
            }}

            {observable.FieldName}.Clear();
            {observable.FieldName}.AddRange(value);
        }}

        if (notify)
        {{
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Add({observable.ListType} value, bool notify = true)
    {{
        {observable.PropName}_Insert({observable.FieldName}.Count, value, notify);
    }}
        
    public void {observable.PropName}_Insert(int index, {observable.ListType} value, bool notify = true)
    {{
        if (index < 0 || index > {observable.FieldName}.Count)
        {{
            return;
        }} 

        {observable.FieldName}.Insert(index, value);
        if (notify)
        {{
            m_{observable.PropName}_OnElementInserted?.Invoke(index, value);
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_Remove({observable.ListType} value, bool notify = true)
    {{
        int index = {observable.FieldName}.IndexOf(value);
        {observable.PropName}_RemoveAt(index, notify);
    }}
        
    public void {observable.PropName}_RemoveAt(int index, bool notify = true)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }} 

        {observable.FieldName}.RemoveAt(index);
        if (notify)
        {{
            m_{observable.PropName}_OnElementRemoved?.Invoke(index);
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}

    public void {observable.PropName}_Set(int index, {observable.ListType} value, bool notify = true)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }} 

        if (SafeEquals({observable.FieldName}[index], value))
        {{
            return;
        }}

        {observable.FieldName}[index] = value;
        if (notify)
        {{
            {observable.PropName}_TriggerElementChanged(index);
        }}
    }}
        
    public void {observable.PropName}_Clear(bool notify = true)
    {{
        if ({observable.FieldName} == null)
        {{
            return;
        }}

        {observable.FieldName}.Clear();
        if (notify)
        {{
            m_{observable.PropName}_OnChanged?.Invoke();
            m_onChanged?.Invoke(this);
        }}
    }}
        
    public void {observable.PropName}_TriggerElementChanged(int index)
    {{
        if (index < 0 || index >= {observable.FieldName}.Count)
        {{
            return;
        }}

        m_{observable.PropName}_OnElementChanged?.Invoke(index);
        m_{observable.PropName}_OnChanged?.Invoke();
        m_onChanged?.Invoke(this);
    }}
    // ====================
";
    }

    private string GeneratePassthrough(PassthroughAttributeConfig passthrough)
    {
        return $@"
    // === Generated Passthrough for {passthrough.FieldName} ===
    public {passthrough.FieldType} {passthrough.PropName}
    {{
        get
        {{
            if ({passthrough.ModelName} == null) {{ return default; }}
            return {passthrough.ModelName}.{passthrough.ModelPropertyName};
        }}
    }}

    public event Action<{passthrough.FieldType}> {passthrough.PropName}_OnChanged
    {{
        add 
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged += value;
        }}
        remove
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged -= value;
        }}
    }}
    
    public void {passthrough.PropName}_Set({passthrough.FieldType} value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(value, notify);
    }}

    public void {passthrough.PropName}_TriggerChanged()
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_TriggerOnChanged();
    }}
    // ====================
";
    }

    private string GeneratePassthroughList(PassthroughAttributeConfig passthrough)
    {
        return $@"
    // === Generated Passthrough for {passthrough.FieldName} ===
    public ReadOnlyCollection<{passthrough.ListType}> {passthrough.PropName}
    {{
        get
        {{
            if ({passthrough.ModelName} == null) {{ return default; }}
            return {passthrough.ModelName}.{passthrough.ModelPropertyName};
        }}
    }}

    public event Action {passthrough.PropName}_OnChanged
    {{
        add 
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged += value;
        }}
        remove
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnChanged -= value;
        }}
    }}

    public event Action<int, {passthrough.ListType}> {passthrough.PropName}_OnElementInserted
    {{
        add 
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementInserted += value;
        }}
        remove
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementInserted -= value;
        }}
    }}

    public event Action<int> {passthrough.PropName}_OnElementRemoved
    {{
        add 
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementRemoved += value;
        }}
        remove
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementRemoved -= value;
        }}
    }}

    public event Action<int> {passthrough.PropName}_OnElementChanged
    {{
        add 
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementChanged += value;
        }}
        remove
        {{
            if ({passthrough.ModelName} == null) {{ return; }}
            {passthrough.ModelName}.{passthrough.ModelPropertyName}_OnElementChanged -= value;
        }}
    }}
        
    public void {passthrough.PropName}_Set(List<{passthrough.ListType}> value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(value, notify);
    }}
        
    public void {passthrough.PropName}_Add({passthrough.ListType} value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Add(value, notify);
    }}
        
    public void {passthrough.PropName}_Insert(int index, {passthrough.ListType} value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Insert(index, value, notify);
    }}
        
    public void {passthrough.PropName}_Remove({passthrough.ListType} value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Remove(value, notify);
    }}
        
    public void {passthrough.PropName}_RemoveAt(int index, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_RemoveAt(index, notify);
    }}
        
    public void {passthrough.PropName}_Set(int index, {passthrough.ListType} value, bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Set(index, value, notify);
    }}
        
    public void {passthrough.PropName}_Clear(bool notify = true)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_Clear(notify);
    }}
        
    public void {passthrough.PropName}_TriggerElementChanged(int index)
    {{
        if ({passthrough.ModelName} == null) {{ return; }}
        {passthrough.ModelName}.{passthrough.ModelPropertyName}_TriggerElementChanged(index);
    }}
    // =================
";
    }
    
    private string GenerateModelInit(ModelGenConfig modelGenConfig)
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append($@"
    protected override void AutoGenInit()
    {{");
        
        foreach (AttributeConfig attributeConfig in modelGenConfig.RelevantAttributes)
        {
            if (attributeConfig is ObservableAttributeConfig observable && observable.FieldIsTypeModel)
            {
                if (observable.IsList)
                {
                    stringBuilder.Append($@"
        if ({observable.FieldName} != null)
        {{
            foreach({observable.ListType} element in {observable.FieldName})
            {{
                {observable.PropName}_BindElementOnChanged(element);
            }}
        }}");
                }
                else
                {
                    stringBuilder.Append($@"
        if ({observable.FieldName} != null)
        {{
            {observable.FieldName}.OnChanged += m_onChanged;
        }}");
                }
            }
            else if (attributeConfig is PassthroughAttributeConfig passthrough)
            {
                if (passthrough.IsList)
                {
                }
                else
                {
                }
            }
        }
        
        stringBuilder.Append($@"
    }}
");   
        
        return stringBuilder.ToString();
    }

    private string GenerateModelOnChangedAction(ModelGenConfig modelGenConfig)
    {
        return $@"
    protected Action<BaseModel> m_onChanged;
    private Action m_onChanged_OnDelegatesChanged;
    public override event Action<BaseModel> OnChanged
    {{
        add
        {{
            m_onChanged += value;
            m_onChanged_OnDelegatesChanged?.Invoke();
        }}
        remove
        {{
            m_onChanged -= value;
            m_onChanged_OnDelegatesChanged?.Invoke();
        }}
    }}
";
    }

    private string GenerateSafeEqualityComparerFunction()
    {
        return $@"
    private bool SafeEquals<T>(T a, T b)
    {{
        return EqualityComparer<T>.Default.Equals(a, b);
    }}";
    }
}